
[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "spearmint"
dynamic = ["version"]

[tool.setuptools_scm]
version_file = "spearmint/_version.py"