name: mypy

on: 
  push:
    paths-ignore:
      - "docs/**"
      - "*.md"

  pull_request:
    paths-ignore:
      - "docs/**"
      - "*.md"

jobs:
  type-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:  
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # cache dependencies
          cache-dependency-path: |
            **/setup.cfg
            **/pyproject.toml
      - name: Install testing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
      - name: Type check with mypy
        run: |
          mypy . --pretty --config-file .mypy.ini