name: lint (ruff) & test (pytest)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - name: Lint with ruff
      uses: actions/checkout@v3
    - uses: chartboost/ruff-action@v1